/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CompanyRouteImport } from './routes/$company'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyIndexRouteImport } from './routes/$company.index'
import { Route as ApiZebraReaderRouteImport } from './routes/api.zebra-reader'
import { Route as CompanyReadersRouteImport } from './routes/$company.readers'
import { Route as CompanyReaderDebugRouteImport } from './routes/$company.reader-debug'
import { Route as CompanyLocationsRouteImport } from './routes/$company.locations'
import { Route as CompanyItemsRouteImport } from './routes/$company.items'
import { Route as CompanyHistoryRouteImport } from './routes/$company.history'
import { Route as CompanyDecoderRouteImport } from './routes/$company.decoder'
import { Route as CompanyDashboardRouteImport } from './routes/$company.dashboard'
import { Route as CompanyBulkUploadRouteImport } from './routes/$company.bulk-upload'
import { Route as CompanyAdminDashboardRouteImport } from './routes/$company.admin-dashboard'
import { Route as CompanyAdminRouteImport } from './routes/$company.admin'
import { Route as ApiZebraReaderCompanyKeyRouteImport } from './routes/api.zebra-reader.$company.$key'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/$company',
  path: '/$company',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIndexRoute = CompanyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompanyRoute,
} as any)
const ApiZebraReaderRoute = ApiZebraReaderRouteImport.update({
  id: '/api/zebra-reader',
  path: '/api/zebra-reader',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyReadersRoute = CompanyReadersRouteImport.update({
  id: '/readers',
  path: '/readers',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyReaderDebugRoute = CompanyReaderDebugRouteImport.update({
  id: '/reader-debug',
  path: '/reader-debug',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyLocationsRoute = CompanyLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyItemsRoute = CompanyItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyHistoryRoute = CompanyHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyDecoderRoute = CompanyDecoderRouteImport.update({
  id: '/decoder',
  path: '/decoder',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyDashboardRoute = CompanyDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyBulkUploadRoute = CompanyBulkUploadRouteImport.update({
  id: '/bulk-upload',
  path: '/bulk-upload',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyAdminDashboardRoute = CompanyAdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyAdminRoute = CompanyAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => CompanyRoute,
} as any)
const ApiZebraReaderCompanyKeyRoute =
  ApiZebraReaderCompanyKeyRouteImport.update({
    id: '/$company/$key',
    path: '/$company/$key',
    getParentRoute: () => ApiZebraReaderRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$company': typeof CompanyRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$company/admin': typeof CompanyAdminRoute
  '/$company/admin-dashboard': typeof CompanyAdminDashboardRoute
  '/$company/bulk-upload': typeof CompanyBulkUploadRoute
  '/$company/dashboard': typeof CompanyDashboardRoute
  '/$company/decoder': typeof CompanyDecoderRoute
  '/$company/history': typeof CompanyHistoryRoute
  '/$company/items': typeof CompanyItemsRoute
  '/$company/locations': typeof CompanyLocationsRoute
  '/$company/reader-debug': typeof CompanyReaderDebugRoute
  '/$company/readers': typeof CompanyReadersRoute
  '/api/zebra-reader': typeof ApiZebraReaderRouteWithChildren
  '/$company/': typeof CompanyIndexRoute
  '/api/zebra-reader/$company/$key': typeof ApiZebraReaderCompanyKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$company/admin': typeof CompanyAdminRoute
  '/$company/admin-dashboard': typeof CompanyAdminDashboardRoute
  '/$company/bulk-upload': typeof CompanyBulkUploadRoute
  '/$company/dashboard': typeof CompanyDashboardRoute
  '/$company/decoder': typeof CompanyDecoderRoute
  '/$company/history': typeof CompanyHistoryRoute
  '/$company/items': typeof CompanyItemsRoute
  '/$company/locations': typeof CompanyLocationsRoute
  '/$company/reader-debug': typeof CompanyReaderDebugRoute
  '/$company/readers': typeof CompanyReadersRoute
  '/api/zebra-reader': typeof ApiZebraReaderRouteWithChildren
  '/$company': typeof CompanyIndexRoute
  '/api/zebra-reader/$company/$key': typeof ApiZebraReaderCompanyKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$company': typeof CompanyRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$company/admin': typeof CompanyAdminRoute
  '/$company/admin-dashboard': typeof CompanyAdminDashboardRoute
  '/$company/bulk-upload': typeof CompanyBulkUploadRoute
  '/$company/dashboard': typeof CompanyDashboardRoute
  '/$company/decoder': typeof CompanyDecoderRoute
  '/$company/history': typeof CompanyHistoryRoute
  '/$company/items': typeof CompanyItemsRoute
  '/$company/locations': typeof CompanyLocationsRoute
  '/$company/reader-debug': typeof CompanyReaderDebugRoute
  '/$company/readers': typeof CompanyReadersRoute
  '/api/zebra-reader': typeof ApiZebraReaderRouteWithChildren
  '/$company/': typeof CompanyIndexRoute
  '/api/zebra-reader/$company/$key': typeof ApiZebraReaderCompanyKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$company'
    | '/login'
    | '/signup'
    | '/$company/admin'
    | '/$company/admin-dashboard'
    | '/$company/bulk-upload'
    | '/$company/dashboard'
    | '/$company/decoder'
    | '/$company/history'
    | '/$company/items'
    | '/$company/locations'
    | '/$company/reader-debug'
    | '/$company/readers'
    | '/api/zebra-reader'
    | '/$company/'
    | '/api/zebra-reader/$company/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/$company/admin'
    | '/$company/admin-dashboard'
    | '/$company/bulk-upload'
    | '/$company/dashboard'
    | '/$company/decoder'
    | '/$company/history'
    | '/$company/items'
    | '/$company/locations'
    | '/$company/reader-debug'
    | '/$company/readers'
    | '/api/zebra-reader'
    | '/$company'
    | '/api/zebra-reader/$company/$key'
  id:
    | '__root__'
    | '/'
    | '/$company'
    | '/login'
    | '/signup'
    | '/$company/admin'
    | '/$company/admin-dashboard'
    | '/$company/bulk-upload'
    | '/$company/dashboard'
    | '/$company/decoder'
    | '/$company/history'
    | '/$company/items'
    | '/$company/locations'
    | '/$company/reader-debug'
    | '/$company/readers'
    | '/api/zebra-reader'
    | '/$company/'
    | '/api/zebra-reader/$company/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRoute: typeof CompanyRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiZebraReaderRoute: typeof ApiZebraReaderRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$company': {
      id: '/$company'
      path: '/$company'
      fullPath: '/$company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$company/': {
      id: '/$company/'
      path: '/'
      fullPath: '/$company/'
      preLoaderRoute: typeof CompanyIndexRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/api/zebra-reader': {
      id: '/api/zebra-reader'
      path: '/api/zebra-reader'
      fullPath: '/api/zebra-reader'
      preLoaderRoute: typeof ApiZebraReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$company/readers': {
      id: '/$company/readers'
      path: '/readers'
      fullPath: '/$company/readers'
      preLoaderRoute: typeof CompanyReadersRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/$company/reader-debug': {
      id: '/$company/reader-debug'
      path: '/reader-debug'
      fullPath: '/$company/reader-debug'
      preLoaderRoute: typeof CompanyReaderDebugRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/$company/locations': {
      id: '/$company/locations'
      path: '/locations'
      fullPath: '/$company/locations'
      preLoaderRoute: typeof CompanyLocationsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/$company/items': {
      id: '/$company/items'
      path: '/items'
      fullPath: '/$company/items'
      preLoaderRoute: typeof CompanyItemsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/$company/history': {
      id: '/$company/history'
      path: '/history'
      fullPath: '/$company/history'
      preLoaderRoute: typeof CompanyHistoryRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/$company/decoder': {
      id: '/$company/decoder'
      path: '/decoder'
      fullPath: '/$company/decoder'
      preLoaderRoute: typeof CompanyDecoderRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/$company/dashboard': {
      id: '/$company/dashboard'
      path: '/dashboard'
      fullPath: '/$company/dashboard'
      preLoaderRoute: typeof CompanyDashboardRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/$company/bulk-upload': {
      id: '/$company/bulk-upload'
      path: '/bulk-upload'
      fullPath: '/$company/bulk-upload'
      preLoaderRoute: typeof CompanyBulkUploadRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/$company/admin-dashboard': {
      id: '/$company/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/$company/admin-dashboard'
      preLoaderRoute: typeof CompanyAdminDashboardRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/$company/admin': {
      id: '/$company/admin'
      path: '/admin'
      fullPath: '/$company/admin'
      preLoaderRoute: typeof CompanyAdminRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/api/zebra-reader/$company/$key': {
      id: '/api/zebra-reader/$company/$key'
      path: '/$company/$key'
      fullPath: '/api/zebra-reader/$company/$key'
      preLoaderRoute: typeof ApiZebraReaderCompanyKeyRouteImport
      parentRoute: typeof ApiZebraReaderRoute
    }
  }
}

interface CompanyRouteChildren {
  CompanyAdminRoute: typeof CompanyAdminRoute
  CompanyAdminDashboardRoute: typeof CompanyAdminDashboardRoute
  CompanyBulkUploadRoute: typeof CompanyBulkUploadRoute
  CompanyDashboardRoute: typeof CompanyDashboardRoute
  CompanyDecoderRoute: typeof CompanyDecoderRoute
  CompanyHistoryRoute: typeof CompanyHistoryRoute
  CompanyItemsRoute: typeof CompanyItemsRoute
  CompanyLocationsRoute: typeof CompanyLocationsRoute
  CompanyReaderDebugRoute: typeof CompanyReaderDebugRoute
  CompanyReadersRoute: typeof CompanyReadersRoute
  CompanyIndexRoute: typeof CompanyIndexRoute
}

const CompanyRouteChildren: CompanyRouteChildren = {
  CompanyAdminRoute: CompanyAdminRoute,
  CompanyAdminDashboardRoute: CompanyAdminDashboardRoute,
  CompanyBulkUploadRoute: CompanyBulkUploadRoute,
  CompanyDashboardRoute: CompanyDashboardRoute,
  CompanyDecoderRoute: CompanyDecoderRoute,
  CompanyHistoryRoute: CompanyHistoryRoute,
  CompanyItemsRoute: CompanyItemsRoute,
  CompanyLocationsRoute: CompanyLocationsRoute,
  CompanyReaderDebugRoute: CompanyReaderDebugRoute,
  CompanyReadersRoute: CompanyReadersRoute,
  CompanyIndexRoute: CompanyIndexRoute,
}

const CompanyRouteWithChildren =
  CompanyRoute._addFileChildren(CompanyRouteChildren)

interface ApiZebraReaderRouteChildren {
  ApiZebraReaderCompanyKeyRoute: typeof ApiZebraReaderCompanyKeyRoute
}

const ApiZebraReaderRouteChildren: ApiZebraReaderRouteChildren = {
  ApiZebraReaderCompanyKeyRoute: ApiZebraReaderCompanyKeyRoute,
}

const ApiZebraReaderRouteWithChildren = ApiZebraReaderRoute._addFileChildren(
  ApiZebraReaderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRoute: CompanyRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiZebraReaderRoute: ApiZebraReaderRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
